#### Import the libraries

In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

from pycaret.classification import *

In [4]:
df = pd.read_csv('../data/final/defects_smells.csv', index_col=0)
df_type = df['Type']
df.shape

(19085, 85)

#### Remove duplicates

In [3]:
duplicate_rows = df[df.duplicated()]
len(duplicate_rows)

61

##### Drop the method-level code smells and the different targets that are not necessary for the model. For instance, this code is set up to the Refused Bequest model. To train other models, comment the Refused Bequest line, and remove the target that you want to model.

In [4]:
df = df.drop('LongName', 1)
df = df.drop('Name', 1)
df = df.drop('Parent', 1)
df = df.drop('Component', 1)
df = df.drop('Path', 1)
df = df.drop('Line', 1)
df = df.drop('EndLine', 1)
df = df.drop('Column', 1)
df = df.drop('EndColumn', 1)
df = df.drop('Type', 1)

df = df.drop('fe', 1)
df = df.drop('dico', 1)
df = df.drop('ic', 1)
df = df.drop('lpl', 1)
df = df.drop('mc', 1)
df = df.drop('ss', 1)
df = df.drop('lm', 1)

#df = df.drop('rb', 1)
df = df.drop('cdsbp', 1)
df = df.drop('dacl', 1)
df = df.drop('lc', 1)
df = df.drop('sc', 1)
df = df.drop('sg', 1)
df = df.drop('gc', 1)

df = df.drop('bug', 1)

#### Check the correlation and remove the high-correlated features from the dataset

In [5]:
corr = df.corr()
threshold = 0.99

columns = np.full((corr.shape[0],), True, dtype=bool)
for i in range(corr.shape[0]):
    for j in range(i+1, corr.shape[0]):
        if corr.iloc[i,j] >= threshold:
            print(df.columns[i],df.columns[j])
            if columns[j]:
                columns[j] = False
selected_columns = df.columns[columns]
high_corr = set(df.columns) - set(selected_columns)
df = df[selected_columns]

LDC LLDC
CLOC TCLOC
NA TNA
NLPA TNLPA
NPA TNPA

In [6]:
df['Type'] = df_type

##### Put the target on the end of the dataframe. Here, as an example, our target is the presence of the Refused Bequest.

In [7]:
results = df.rb.values
df = df.drop('rb', axis=1)
df['rb'] = results

#### Setup the model creation with pycaret

In [8]:
s = setup(data=df, target='rb', feature_selection=True,
          remove_multicollinearity=True,
          multicollinearity_threshold=0.85,
          feature_selection_method='boruta',
          fix_imbalance=True, fold=10)

In [9]:
df = get_config('X')

#### Plot the features

In [11]:
selected_features = list(get_config('X').columns)
with open('../../results/features.csv', 'w') as f:
     f.write("\n".join(selected_features))

##### Train the models. In this code the model was trained for the Refused Bequest smell. From all models, we selected the top-5 in terms of F1.

In [12]:
top5_models = compare_models(n_select=5, sort='f1')

#### Tune the models

In [13]:
tuned_top5 = [
  tune_model(
    i,
    n_iter=30,
    optimize="f1",
    search_library='optuna',
    choose_better=True,
    early_stopping=True)
  for i in top5_models
  ]

#### Ensemble the top-5 models

In [14]:
blended_models = blend_models(
  tuned_top5,
  choose_better=True,
  optimize="f1")

In [15]:
pred = predict_model(blended_models)

In [16]:
result = pull()

#### Plot the ensemble model

In [17]:
result.to_csv('../../results/models.csv')

#### Finalize and save the ensemble model

In [18]:
final_best = finalize_model(blended_models)
save_model(final_best, '../../results/rb/model')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=[], target='rb',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_strategy=...
                                             max_features=0.9779201704921807,
                                             max_leaf_nodes=None,
                                             min_impurity_decrease=3.746660669697568e-05,
                                             min_impurity_split=None,
                                             min_samples_leaf=5,
                                             min_samples_split=2,
                                             min_weight_fraction_leaf=0.0,
                                             n_estimators=134,
                                             n_iter_no_change=None,
                                             presort='deprecated',
                                             random_state=3426,
                                             subsample=0.6397315018084915,
                                             tol=0.0001, validation_fraction=0.1,
                                             verbose=0, warm_start=False)]],
          verbose=False),
 '../../results/rb/model.pkl')

#### Interpret the ensemble model

In [20]:
interpret_model(tuned_top5[0], save=True)